
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            5896
     no. of nonzeroes in lower triangle of a =           68512
     no. of nonzeroes in the factor l        =          369878
     ratio of nonzeroes in factor (min/max)  =          0.9172
     number of super nodes                   =             416
     maximum order of a front matrix         =             146
     maximum size of a front matrix          =           10731
     maximum size of a front trapezoid       =            7956
     no. of floating point ops for factor    =      2.1690D+07
     no. of floating point ops for solve     =      1.2266D+06
     ratio of flops for factor (min/max)     =          0.8875
     ratio of allocated memory (max/min)     =          1.0738
     Number of positive pivots               =            5896
     Number of negative pivots               =               0
     Number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000171
     time (cpu & wall) for ordering          =        0.015625        0.010965
     time (cpu & wall) for other matrix prep =        0.000000        0.003451
     time (cpu & wall) for value input       =        0.000000        0.000261
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011178

     no input or output performed

  Solver Memory allocated on core    0       =        2.041 MB
  Solver Memory allocated on core    1       =        1.982 MB
  Solver Memory allocated on core    2       =        1.983 MB
  Solver Memory allocated on core    3       =        1.901 MB
  Total Solver Memory allocated by all cores =        7.908 MB

